OBJS     = clock.o

BINARY   = application

#CFLAGS   = -O0 -ggdb3
CFLAGS   = -O3 -ggdb3

#LDLIBS   = 
#LDSCRIPT = ../stm32f769i-discovery.ld
DEVICE      = stm32f769nih6

include ../../Makefile.include
